module Erogamescape
  VERSION: String
  class SqlError < StandardError
  end
  class WrongSqlError < StandardError
  end
  class RuntimeSqlError < StandardError
  end

  private def self.parse_response_html: (String html) -> Array[Hash[String, String]]
  private def self.post_sql: (String sql) -> String
  def self.query: (String sql) -> Array[Hash[String, String]]
end
